### ISSUE TITLE
Can't set Zigbee Attributes

### ISSUE THREAD

**Issue by harrismck** [pvvx/ZigbeeTLc#101]
According to the docs, I should be able to set min/max comfort temp/humidity values via Zigbee attributes, but those attributes don't seem to exist. In ZHA, looking at the UserInterface cluster, I only see these three attributes:
![image](https://github.com/pvvx/ZigbeeTLc/assets/11249652/1ecb8c1d-f089-4249-a05c-3d98f6991ddf)
I tried setting the value manually with the zha.set_zigbee_cluster_attribute service call, but I get this error:
`Unexpected error for call_service at pos 1: Cluster 204 not found on endpoint 1 while writing attribute 102 with value 1800`
![image](https://github.com/pvvx/ZigbeeTLc/assets/11249652/27dcfb16-ba7a-4fc3-8a4f-97457f39b8dc)

My device is a LYWSD03MMC-z by Xiaomi, and I have just flashed the latest firmware (reported as  0x01213001 in HA)

**Comment by pvvx** [comment]
ClusterID: 0x0204 (HEX) -> 516 (DEC)
Attr: 0x0102 (HEX) -> 258 (DEC)

```
service: zha.set_zigbee_cluster_attribute
data:
  cluster_type: out
  value: "1800"
  ieee: a4:c1:38:xx:xx:xx:xx:xx
  endpoint_id: 1
  cluster_id: 516
  attribute: 258
```
