### ISSUE TITLE
z2m showing wrong version

### ISSUE THREAD

**Issue by propi62** [pvvx/ZigbeeTLc#180]
after every update some sensors show a wrong version number.
i am pretty sure, the sensors showing the old version were updated succesfull.
repairing them does not solve the problem.

![Image](https://github.com/user-attachments/assets/005b4812-419c-4bcd-a6ca-6b2307c4ccfb)

**Comment by pvvx** [comment]
![Image](https://github.com/user-attachments/assets/569de419-325e-4b25-b821-57f06275e1b1)

**Comment by pvvx** [comment]
```
zha_toolkit_version: v1.1.27
zigpy_version: 0.77.1
zigpy_rf_version: 0.43.0
ieee_org: update.xiaomi_lywsd03mmc_z_firmware_2
ieee: a4:c1:38:d8:40:5b:e6:8d
command: scan_device
command_data: null
start_time: "2025-04-07T09:05:36.572945+00:00"
errors: []
params:
  dir: 0
  tries: 1
  expect_reply: true
  args: []
  kwargs: {}
  read_before_write: true
  read_after_write: true
scan:
  ieee: a4:c1:38:d8:40:5b:e6:8d
  nwk: "0x9e84"
  model: LYWSD03MMC-z
  manufacturer: Xiaomi
  manufacturer_id: "0x4417"
  endpoints:
    - id: 1
      device_type: "0x0302"
      profile: "0x0104"
      in_clusters:
        "0x0000":
          cluster_id: "0x0000"
          title: Basic
          name: basic
          attributes:
            "0x0000":
              attribute_id: "0x0000"
              attribute_name: zcl_version
              value_type:
                - "0x20"
                - uint8_t
                - Analog
              access: READ
              access_acl: 1
              manf_id: 4417
              attribute_value: 3
            "0x0001":
              attribute_id: "0x0001"
              attribute_name: app_version
              value_type:
                - "0x20"
                - uint8_t
                - Analog
              access: READ
              access_acl: 1
              manf_id: 4417
              attribute_value: 37
            "0x0002":
              attribute_id: "0x0002"
              attribute_name: stack_version
              value_type:
                - "0x20"
                - uint8_t
                - Analog
              access: READ
              access_acl: 1
              manf_id: 4417
              attribute_value: 49
            "0x0003":
              attribute_id: "0x0003"
              attribute_name: hw_version
              value_type:
                - "0x20"
                - uint8_t
                - Analog
              access: READ
              access_acl: 1
              manf_id: 4417
              attribute_value: 10
            "0x0004":
              attribute_id: "0x0004"
              attribute_name: manufacturer
              value_type:
                - "0x42"
                - CharacterString
                - Discrete
              access: READ|WRITE
              access_acl: 3
              manf_id: 4417
              attribute_value: Xiaomi
            "0x0005":
              attribute_id: "0x0005"
              attribute_name: model
              value_type:
                - "0x42"
                - CharacterString
                - Discrete
              access: READ|WRITE
              access_acl: 3
              manf_id: 4417
              attribute_value: LYWSD03MMC-z
            "0x0006":
              attribute_id: "0x0006"
              attribute_name: date_code
              value_type:
                - "0x42"
                - CharacterString
                - Discrete
              access: READ
              access_acl: 1
              manf_id: 4417
              attribute_value: "20250313"
            "0x0007":
              attribute_id: "0x0007"
              attribute_name: power_source
              value_type:
                - "0x30"
                - enum8
                - Discrete
              access: READ
              access_acl: 1
              manf_id: 4417
              attribute_value: 3
            "0x0012":
              attribute_id: "0x0012"
              attribute_name: device_enabled
              value_type:
                - "0x10"
                - Bool
                - Discrete
              access: READ|WRITE
              access_acl: 3
              manf_id: 4417
              attribute_value: 1
            "0x4000":
              attribute_id: "0x4000"
              attribute_name: sw_build_id
              value_type:
                - "0x42"
                - CharacterString
                - Discrete
              access: READ
              access_acl: 1
              manf_id: 4417
              attribute_value: 3001-0125
            "0xfffd":
              attribute_id: "0xfffd"
              attribute_name: cluster_revision
              value_type:
                - "0x21"
                - uint16_t
                - Analog
              access: READ
              access_acl: 1
              manf_id: 4417
              attribute_value: 1
          commands_received: {}
          commands_generated: {}
        "0x0001":
          cluster_id: "0x0001"
          title: Power Configuration
          name: power
          attributes:
            "0x0020":
              attribute_id: "0x0020"
              attribute_name: battery_voltage
              value_type:
                - "0x20"
                - uint8_t
                - Analog
              access: READ|REPORT
              access_acl: 5
              manf_id: 4417
              attribute_value: 27
            "0x0021":
              attribute_id: "0x0021"
              attribute_name: battery_percentage_remaining
              value_type:
                - "0x20"
                - uint8_t
                - Analog
              access: READ|REPORT
              access_acl: 5
              manf_id: 4417
              attribute_value: 112
            "0xfffd":
              attribute_id: "0xfffd"
              attribute_name: cluster_revision
              value_type:
                - "0x21"
                - uint16_t
                - Analog
              access: READ
              access_acl: 1
              manf_id: 4417
              attribute_value: 1
          commands_received: {}
          commands_generated: {}
        "0x0003":
          cluster_id: "0x0003"
          title: Identify
          name: identify
          attributes:
            "0x0000":
              attribute_id: "0x0000"
              attribute_name: identify_time
              value_type:
                - "0x21"
                - uint16_t
                - Analog
              access: READ|WRITE
              access_acl: 3
              manf_id: 4417
              attribute_value: 0
            "0xfffd":
              attribute_id: "0xfffd"
              attribute_name: cluster_revision
              value_type:
                - "0x21"
                - uint16_t
                - Analog
              access: READ
              access_acl: 1
              manf_id: 4417
              attribute_value: 1
          commands_received: {}
          commands_generated: {}
        "0x0020":
          cluster_id: "0x0020"
          title: Poll Control
          name: poll_control
          attributes:
            "0x0000":
              attribute_id: "0x0000"
              attribute_name: checkin_interval
              value_type:
                - "0x23"
                - uint32_t
                - Analog
              access: READ|WRITE
              access_acl: 3
              manf_id: 4417
              attribute_value: 13200
            "0x0001":
              attribute_id: "0x0001"
              attribute_name: long_poll_interval
              value_type:
                - "0x23"
                - uint32_t
                - Analog
              access: READ
              access_acl: 1
              manf_id: 4417
              attribute_value: 120
            "0x0002":
              attribute_id: "0x0002"
              attribute_name: short_poll_interval
              value_type:
                - "0x21"
                - uint16_t
                - Analog
              access: READ
              access_acl: 1
              manf_id: 4417
              attribute_value: 2
            "0x0003":
              attribute_id: "0x0003"
              attribute_name: fast_poll_timeout
              value_type:
                - "0x21"
                - uint16_t
                - Analog
              access: READ|WRITE
              access_acl: 3
              manf_id: 4417
              attribute_value: 40
            "0x0004":
              attribute_id: "0x0004"
              attribute_name: checkin_interval_min
              value_type:
                - "0x23"
                - uint32_t
                - Analog
              access: READ
              access_acl: 1
              manf_id: 4417
              attribute_value: 0
            "0x0005":
              attribute_id: "0x0005"
              attribute_name: long_poll_interval_min
              value_type:
                - "0x23"
                - uint32_t
                - Analog
              access: READ
              access_acl: 1
              manf_id: 4417
              attribute_value: 120
            "0x0006":
              attribute_id: "0x0006"
              attribute_name: fast_poll_timeout_max
              value_type:
                - "0x21"
                - uint16_t
                - Analog
              access: READ
              access_acl: 1
              manf_id: 4417
              attribute_value: 40
            "0xfffd":
              attribute_id: "0xfffd"
              attribute_name: cluster_revision
              value_type:
                - "0x21"
                - uint16_t
                - Analog
              access: READ
              access_acl: 1
              manf_id: 4417
              attribute_value: 1
          commands_received: {}
          commands_generated: {}
        "0x0204":
          cluster_id: "0x0204"
          title: Thermostat User Interface Configuration
          name: thermostat_ui
          attributes:
            "0x0000":
              attribute_id: "0x0000"
              attribute_name: temperature_display_mode
              value_type:
                - "0x30"
                - enum8
                - Discrete
              access: READ|WRITE
              access_acl: 3
              manf_id: 4417
              attribute_value: 0
            "0x0002":
              attribute_id: "0x0002"
              attribute_name: schedule_programming_visibility
              value_type:
                - "0x30"
                - enum8
                - Discrete
              access: READ|WRITE
              access_acl: 3
              manf_id: 4417
              attribute_value: 0
            "0x0100":
              attribute_id: "0x0100"
              attribute_name: temperature_offset
              value_type:
                - "0x29"
                - int16s
                - Analog
              access: READ|WRITE
              access_acl: 3
              manf_id: 4417
              attribute_value: 0
            "0x0101":
              attribute_id: "0x0101"
              attribute_name: humidity_offset
              value_type:
                - "0x29"
                - int16s
                - Analog
              access: READ|WRITE
              access_acl: 3
              manf_id: 4417
              attribute_value: 0
            "0x0102":
              attribute_id: "0x0102"
              attribute_name: comfort_temperature_min
              value_type:
                - "0x29"
                - int16s
                - Analog
              access: READ|WRITE
              access_acl: 3
              manf_id: 4417
              attribute_value: 2000
            "0x0103":
              attribute_id: "0x0103"
              attribute_name: comfort_temperature_max
              value_type:
                - "0x29"
                - int16s
                - Analog
              access: READ|WRITE
              access_acl: 3
              manf_id: 4417
              attribute_value: 2500
            "0x0104":
              attribute_id: "0x0104"
              attribute_name: comfort_humidity_min
              value_type:
                - "0x21"
                - uint16_t
                - Analog
              access: READ|WRITE
              access_acl: 3
              manf_id: 4417
              attribute_value: 4000
            "0x0105":
              attribute_id: "0x0105"
              attribute_name: comfort_humidity_max
              value_type:
                - "0x21"
                - uint16_t
                - Analog
              access: READ|WRITE
              access_acl: 3
              manf_id: 4417
              attribute_value: 6000
            "0x0106":
              attribute_id: "0x0106"
              attribute_name: display
              value_type:
                - "0x30"
                - enum8
                - Discrete
              access: READ|WRITE
              access_acl: 3
              manf_id: 4417
              attribute_value: 0
            "0x0107":
              attribute_id: "0x0107"
              attribute_name: measurement_interval
              value_type:
                - "0x20"
                - uint8_t
                - Analog
              access: READ|WRITE
              access_acl: 3
              manf_id: 4417
              attribute_value: 30
            "0xfffd":
              attribute_id: "0xfffd"
              attribute_name: "65533"
              value_type:
                - "0x21"
                - uint16_t
                - Analog
              access: READ
              access_acl: 1
              manf_id: 4417
              attribute_value: 1
          commands_received: {}
          commands_generated: {}
        "0x0402":
          cluster_id: "0x0402"
          title: Temperature Measurement
          name: temperature
          attributes:
            "0x0000":
              attribute_id: "0x0000"
              attribute_name: measured_value
              value_type:
                - "0x29"
                - int16s
                - Analog
              access: READ|REPORT
              access_acl: 5
              manf_id: 4417
              attribute_value: 2030
            "0x0001":
              attribute_id: "0x0001"
              attribute_name: min_measured_value
              value_type:
                - "0x29"
                - int16s
                - Analog
              access: READ
              access_acl: 1
              manf_id: 4417
              attribute_value: -5000
            "0x0002":
              attribute_id: "0x0002"
              attribute_name: max_measured_value
              value_type:
                - "0x29"
                - int16s
                - Analog
              access: READ
              access_acl: 1
              manf_id: 4417
              attribute_value: 17500
            "0x0003":
              attribute_id: "0x0003"
              attribute_name: tolerance
              value_type:
                - "0x21"
                - uint16_t
                - Analog
              access: READ|REPORT
              access_acl: 5
              manf_id: 4417
              attribute_value: 0
            "0xfffd":
              attribute_id: "0xfffd"
              attribute_name: cluster_revision
              value_type:
                - "0x21"
                - uint16_t
                - Analog
              access: READ
              access_acl: 1
              manf_id: 4417
              attribute_value: 1
          commands_received: {}
          commands_generated: {}
        "0x0405":
          cluster_id: "0x0405"
          title: Relative Humidity Measurement
          name: humidity
          attributes:
            "0x0000":
              attribute_id: "0x0000"
              attribute_name: measured_value
              value_type:
                - "0x21"
                - uint16_t
                - Analog
              access: READ|REPORT
              access_acl: 5
              manf_id: 4417
              attribute_value: 3579
            "0x0001":
              attribute_id: "0x0001"
              attribute_name: min_measured_value
              value_type:
                - "0x21"
                - uint16_t
                - Analog
              access: READ
              access_acl: 1
              manf_id: 4417
              attribute_value: 0
            "0x0002":
              attribute_id: "0x0002"
              attribute_name: max_measured_value
              value_type:
                - "0x21"
                - uint16_t
                - Analog
              access: READ
              access_acl: 1
              manf_id: 4417
              attribute_value: 9999
            "0x0003":
              attribute_id: "0x0003"
              attribute_name: tolerance
              value_type:
                - "0x21"
                - uint16_t
                - Analog
              access: READ|REPORT
              access_acl: 5
              manf_id: 4417
              attribute_value: 0
            "0xfffd":
              attribute_id: "0xfffd"
              attribute_name: cluster_revision
              value_type:
                - "0x21"
                - uint16_t
                - Analog
              access: READ
              access_acl: 1
              manf_id: 4417
              attribute_value: 1
          commands_received: {}
          commands_generated: {}
      out_clusters:
        "0x0019":
          cluster_id: "0x0019"
          title: Ota
          name: ota
          attributes:
            "0x0000":
              attribute_id: "0x0000"
              attribute_name: upgrade_server_id
              value_type:
                - "0xf0"
                - EUI64
                - Discrete
              access: READ
              access_acl: 1
              manf_id: 4417
              attribute_value:
                - 158
                - 117
                - 217
                - 254
                - 255
                - 226
                - 10
                - 104
            "0x0001":
              attribute_id: "0x0001"
              attribute_name: file_offset
              value_type:
                - "0x23"
                - uint32_t
                - Analog
              access: READ
              access_acl: 1
              manf_id: 4417
              attribute_value: 4294967295
            "0x0002":
              attribute_id: "0x0002"
              attribute_name: current_file_version
              value_type:
                - "0x23"
                - uint32_t
                - Analog
              access: READ
              access_acl: 1
              manf_id: 4417
              attribute_value: 19214337
            "0x0003":
              attribute_id: "0x0003"
              attribute_name: current_zigbee_stack_version
              value_type:
                - "0x21"
                - uint16_t
                - Analog
              access: READ
              access_acl: 1
              manf_id: 4417
              attribute_value: 2
            "0x0004":
              attribute_id: "0x0004"
              attribute_name: downloaded_file_version
              value_type:
                - "0x23"
                - uint32_t
                - Analog
              access: READ
              access_acl: 1
              manf_id: 4417
              attribute_value: 4294967295
            "0x0005":
              attribute_id: "0x0005"
              attribute_name: downloaded_zigbee_stack_version
              value_type:
                - "0x21"
                - uint16_t
                - Analog
              access: READ
              access_acl: 1
              manf_id: 4417
              attribute_value: 65535
            "0x0006":
              attribute_id: "0x0006"
              attribute_name: image_upgrade_status
              value_type:
                - "0x30"
                - enum8
                - Discrete
              access: READ
              access_acl: 1
              manf_id: 4417
              attribute_value: 0
            "0x0007":
              attribute_id: "0x0007"
              attribute_name: manufacturer_id
              value_type:
                - "0x21"
                - uint16_t
                - Analog
              access: READ
              access_acl: 1
              manf_id: 4417
              attribute_value: 4417
            "0x0008":
              attribute_id: "0x0008"
              attribute_name: image_type_id
              value_type:
                - "0x21"
                - uint16_t
                - Analog
              access: READ
              access_acl: 1
              manf_id: 4417
              attribute_value: 65535
            "0x0009":
              attribute_id: "0x0009"
              attribute_name: minimum_block_req_delay
              value_type:
                - "0x21"
                - uint16_t
                - Analog
              access: READ
              access_acl: 1
              manf_id: 4417
              attribute_value: 0
            "0xfffd":
              attribute_id: "0xfffd"
              attribute_name: cluster_revision
              value_type:
                - "0x21"
                - uint16_t
                - Analog
              access: READ
              access_acl: 1
              manf_id: 4417
              attribute_value: 1
          commands_received: {}
          commands_generated: {}
success: true
```
