### ISSUE TITLE
ZHA - Setting offsets for temperature and humidity

### ISSUE THREAD

**Issue by pvvx** [pvvx/ZigbeeTLc#30]
Available starting from firmware version 0.1.1.6.

## Offset for temperature.

The temperature offset is set in 0.1 C steps.
The minimum value is -127 (-12.7 C).
The maximum value is 127 (+12.7 C).

![image](https://github.com/pvvx/ZigbeeTLc/assets/12629515/b5b277db-0bee-405e-a382-d5f4105d0222)

---

## Offset for humidity.

The humidity offset is set in 0.1 % steps.
The minimum value is -127 (-12.7 %).
The maximum value is 127 (+12.7 %).

![image](https://github.com/pvvx/ZigbeeTLc/assets/12629515/45fdc679-1365-43d2-bcaa-e3e77e0f255c)

**Comment by thkrmr** [comment]
@pvvx sw_build_id = `3001-0117`

ZHA Write Attribute throws an error, logs say `Exception: InCluster 0x0204 not found for '...', endpoint 1`
What could be the issue, do you know? Thank you.

**Comment by pvvx** [comment]
If a version update via OTA was used, then the thermometer must be registered again.

The "UserInterface" cluster should appear in "Manage Zigbee device":

![image](https://github.com/pvvx/ZigbeeTLc/assets/12629515/4c3c319e-23a2-46ce-8be4-13c7f4f12f1e)

![image](https://github.com/pvvx/ZigbeeTLc/assets/12629515/e14f0e78-eede-4a14-9da2-8039c5134f6d)

**Comment by thkrmr** [comment]
> If a version update via OTA was used, then the thermometer must be registered again.

@pvvx indeed I pushed the update via OTA. Thank you, will try.

**Comment by gacopl** [comment]
hi in Zigbee2MQTT  I get cluster 516 has no command 256, when trying to set offset
i flashed 03MMC with Telink over bluetooth, re registered couple times I am sure i have correct firmware 1118

"softwareBuildID": "3001-0118",

Am i doing something wrong ?

**Comment by gacopl** [comment]
> @gacopl  Can you try this PR that add temp/humidifty calibration and others attributes to UI?
> https://github.com/Koenkk/zigbee-herdsman-converters/pull/6939

Don't know how to test tbh using official releases only

**Comment by naimadfpv** [comment]
> @gacopl You need to paste code from PR description to new file and add refernece to this file in `customization.yaml`. For details, see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html

Would be very nice to set these values in the UI. 
Everytime I forgot the value "516" and have to look at it here. 

I also think that a lot of users dont know that this is possible with zha.

**Comment by naimadfpv** [comment]
Using pvvx firmware because i switched from zha to z2m. 
If i now calibrate temp offset it’s showing in z2m but not on the display.

**Comment by f-sh1372** [comment]
Hi
Thanks for your projects. it is so useull.
I flashed the Zigbee fw using your method. everything works fine but one of my sensors, shows humidity incorrect.
I imported sensor in ZHA using your method.
I have both "skyconnect" and "sonoff zigbee 3.0 USB dongle".
I used zha toolkit and after "Read/Write  Attribute" it shows this log and has error. does it relevant to device's sleep mode?
I changed Tries to 100 but not success. 
I am grateful for your support and guidanc.
![zha toolkit01](https://github.com/pvvx/ZigbeeTLc/assets/169527195/5a70cee4-6328-4746-a095-19d0cc9ca3f6)

**Comment by pvvx** [comment]
ZHA has been updated with Zigpy features.
ZHA Toolkit has not been updated for the new version of Zigpy -> Some ZHA Toolkit functions do not work.

Home Assistant Core logs:
```
WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration zha_toolkit which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
```

**Comment by pvvx** [comment]
After updating via Zigbee OTA to version 0.1.2.1, it is advisable to delete the device in the ZHA and re-pair the device.

![image](https://github.com/pvvx/ZigbeeTLc/assets/12629515/15038ebe-1e36-43c0-885f-2e58fe777bd6)

```
zha_toolkit_version: v1.1.10
zigpy_version: 0.63.5
zigpy_rf_version: 0.38.1
ieee_org: update.xiaomi_lywsd03mmc_z_firmware
ieee: a4:c1:38:0b:5e:ed:85:b7
command: attr_read
command_data: null
start_time: "2024-05-15T07:52:59.020252+00:00"
errors: []
params:
  endpoint_id: 1
  cluster_id: 516
  attr_id: 257
  dir: 0
  tries: 1
  expect_reply: true
  args: []
  read_before_write: true
  read_after_write: true
attr_type: "0x29"
write_is_equal: false
result_read:
  - "257": 0
  - {}
success: true
```
